include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

image: node:16

cache:
  paths:
    - node_modules/
    - .next/cache/

.prepare:
  before_script:
    - node -v
    - yarn -v
    - cp .env.example .env
    - yarn install --frozen-lockfile --silent
    - curl -fsSL https://bun.sh/install | bash
    - echo "BUN_INSTALL="/home/gitpod/.bun"" >> $HOME/.bashrc
    - echo "PATH="$BUN_INSTALL/bin:$PATH"" >> $HOME/.bashrc

lint:
  extends: .prepare
  script:
    - bun run lint

prettier:
  extends: .prepare
  script:
    - bun run prettier:check

generate:
  extends: .prepare
  script:
    - bun run generate

typecheck:
  extends: .prepare
  script:
    - bun run generate
    - bun run typecheck

build:
  extends: .prepare
  script:
    - bun run build

graphcdn:
  script:
    - npx graphcdn push
  only:
    - main

migrate:
  script:
    - npx prisma migrate reset --force
  when: manual

# Remove after Devparty release
seed:
  extends: .prepare
  script:
    - DATABASE_URL=$PROD_DATABASE_URL bun run prisma:seed
  only:
    - main
  when: manual

housekeeping:
  before_script: []
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/housekeeping
  only:
    - main
