tasks:
  - name: Database
    before: docker-compose up
  - name: Dev Server
    init: >
      npm install;
      cp .env.example .env;
    command: >
      npm run migrate;
      npm run dev;

ports:
  - port: 3000
    onOpen: open-preview
