image: node:latest

stages:
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/

before_script:
  - cp .env.example .env
  - yarn install --frozen-lockfile --silent

Lint 🌟:
  stage: test
  script:
    - yarn lint

Prettier 📚:
  stage: test
  script:
    - yarn prettier:check

Generate 👷‍♂️:
  stage: test
  script:
    - yarn generate
