include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

image: node:latest

variables:
  SAST_EXCLUDED_PATHS: 'node_modules, .next, yarn.lock'
  SECRET_DETECTION_EXCLUDED_PATHS: 'node_modules, .next, yarn.lock'

cache:
  paths:
    - node_modules/
    - .next/cache/

.prepare:
  before_script:
    - cp .env.example .env
    - yarn install --frozen-lockfile --silent

lint:
  extends: .prepare
  script:
    - yarn lint

prettier:
  extends: .prepare
  script:
    - yarn prettier:check

generate:
  extends: .prepare
  script:
    - yarn generate

typecheck:
  extends: .prepare
  script:
    - yarn generate
    - yarn typecheck

build:
  extends: .prepare
  script:
    - yarn build

migrate:
  extends: .prepare
  script:
    - yarn prisma migrate reset --force
    - yarn prisma migrate deploy
  only:
    - main
  when: manual

deploy_review:
  before_script: []
  script:
    - echo 'Deploying review app to Vercel'
    - yarn global add vercel
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://devparty-git-$CI_COMMIT_REF_NAME-devparty.vercel.app
  after_script:
    - vercel inspect "devparty-git-$CI_COMMIT_REF_NAME-devparty.vercel.app" --token='$VERCEL_TOKEN' --scope=devparty
  only:
    - branches
  except:
    - main

housekeeping:
  before_script: []
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/housekeeping
  only:
    - main
