image: node:latest

stages:
  - test
  - clean

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/
    - .next/cache/

before_script:
  - cp .env.example .env
  - yarn install --frozen-lockfile --silent

Lint 🌟:
  stage: test
  script:
    - yarn lint

Prettier 📚:
  stage: test
  script:
    - yarn prettier:check

Generate 🧞‍♂️:
  stage: test
  script:
    - yarn generate

Typecheck 🧐:
  stage: test
  script:
    - yarn generate
    - yarn typecheck

Build 👷‍♂️:
  stage: test
  script:
    - yarn build

Housekeeping ✨:
  stage: clean
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/housekeeping
  only:
    - main

Merged Branches 🗑:
  stage: clean
  script:
    - curl --request DELETE --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/merged_branches
  only:
    - main
