image: node:latest

services:
  - postgres:latest

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - cp .env.example .env

Lint:
  stage: test
  script:
    - npm run lint

Build:
  stage: build
  script:
    - npm run build
