image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup
    before: |
      redis-server &
      gp sync-done redis
    init: scripts/gp-init.sh
    command: |
      yarn codegen:graphql --watch &
      gp sync-done codegen
      export BASE_URL=`gp url 3000`
      yarn dev

  - command: scripts/gp-welcome.sh

ports:
  - port: 3000 # Web app
    onOpen: notify
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 3306 # MySQL
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - esbenp.prettier-vscode
    - prisma.prisma
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - bradlc.vscode-tailwindcss
    - pkief.material-icon-theme
    - juanblanco.solidity
