image: node:latest

services:
  - postgres:latest

stages:
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/

before_script:
  - yarn install
  - cp .env.example .env

Lint 🌟:
  stage: test
  script:
    - yarn lint

Prettier 📚:
  stage: test
  script:
    - yarn prettier:check

Build 👷‍♂️:
  stage: test
  script:
    - yarn generate
