image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - cp .env.example .env
  - yarn install --frozen-lockfile --silent

Lint 🌟:
  stage: test
  script:
    - yarn lint

Prettier 📚:
  stage: test
  script:
    - yarn prettier:check

Generate 🧞‍♂️:
  stage: test
  script:
    - yarn generate

Typecheck 🧐:
  stage: test
  script:
    - yarn generate
    - yarn typecheck

Build 👷‍♂️:
  stage: test
  script:
    - yarn build
