image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup
    before: redis-server &
    init: |
      yarn install --frozen-lockfile --silent --network-timeout 100000
      cp .env.example .env
      gp await-port 3306
      yarn prisma:migrate
      yarn prisma:seed
      yarn prepare
      gp sync-done setup
    command: yarn codegen:graphql --watch
  - name: Hardhat
    init: gp sync-await setup;
    command: npx hardhat node
  - name: Dev Server
    init: gp sync-await setup
    command: |
      gp await-port 8545
      npx hardhat run scripts/deploy.js --network localhost
      echo "BASE_URL=\"$(gp url 3000)\"" >> .env
      yarn dev
  - init: gp sync-await setup;
    command: |
      printf "Waiting for server to boot ⏰"
      clear

ports:
  - port: 3000 # Web app
    onOpen: open-preview
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 3306 # MySQL
    onOpen: ignore
  - port: 8545 # Hardhat
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - github.github-vscode-theme
    - gitlab.gitlab-workflow
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - editorconfig.editorconfig
    - pkief.material-icon-theme
    - juanblanco.solidity
