include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

image: node:latest

stages:
  - test
  - build
  - deploy

variables:
  SAST_EXCLUDED_PATHS: 'node_modules, yarn.lock'

cache:
  paths:
    - node_modules/
    - .next/cache/
