image: gitpod/workspace-postgres

tasks:
  - name: Setup
    before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    init: >
      yarn --network-timeout 100000;
      cp .env.example .env;
      yarn prisma:migrate;
      yarn prisma:seed;
      yarn prepare;
      gp sync-done setup;
    command: yarn codegen:graphql --watch
  - name: Prisma Studio
    init: gp sync-await setup
    command: BROWSER=none yarn prisma studio
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 5555
    onOpen: notify
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - github.github-vscode-theme
    - gitlab.gitlab-workflow
    - bradlc.vscode-tailwindcss
