image: node:latest

services:
  - postgres:latest

stages:
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - cp .env.example .env

Lint 🌟:
  stage: test
  script:
    - npm run lint
  artifacts:
    expire_in: 1 day
