image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup
    before: redis-server &
    init: |
      yarn install --frozen-lockfile --silent --network-timeout 100000
      curl -fsSL https://bun.sh/install | bash
      cp .env.example .env
      gp await-port 3306
      bun run prisma:migrate
      bun run prisma:seed
      bun run prepare
      gp sync-done setup
    command: bun run codegen:graphql --watch
  - name: Dev Server
    init: gp sync-await setup
    command: |
      echo "BASE_URL=\"$(gp url 3000)\"" >> .env
      bun run dev
  - name: Bash
    init: gp sync-await setup
    command: |
      printf "Waiting for server to boot ⏰"
      clear

ports:
  - port: 3000 # Web app
    onOpen: open-preview
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 3306 # MySQL
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - esbenp.prettier-vscode
    - prisma.prisma
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - bradlc.vscode-tailwindcss
    - pkief.material-icon-theme
    - juanblanco.solidity
