image: gitpod/workspace-postgres

tasks:
  - name: Setup
    init: >
      yarn install;
      cp .env.example .env;
    command: >
      yarn migrate:dev;
      yarn prepare;
      gp sync-done setup;
      yarn codegen:graphql --watch;
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev

ports:
  - port: 3000
    onOpen: notify

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-rename-tag
    - github.github-vscode-theme
