language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "16"

before_install:
  - npm config set python `which python`

script:
  - yarn generate
  - yarn typecheck
  - yarn prettier:check
  - yarn lint
  - yarn build
