language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "17"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - gcc-4.9
      - g++-4.9

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if [[ $(node -v) =~ v1[01] ]]; then
        export CC="gcc-4.9";
        export CXX="g++-4.9";
        export LINK="gcc-4.9";
        export LINKXX="g++-4.9";
      else
        export CC="gcc-4.7";
        export CXX="g++-4.7";
        export LINK="gcc-4.7";
        export LINKXX="g++-4.7";
      fi
    fi

script:
  - yarn lint
