pool:
  name: Azure Pipelines

steps:
  - script: 'yarn install --frozen-lockfile --silent'
    displayName: 'Install Dependencies'

  - script: 'yarn lint'
    displayName: 'Lint'

  - script: 'yarn prettier:check'
    displayName: 'Prettier Check'

  - script: 'yarn generate'
    displayName: 'Generate'

  - script: 'yarn generate && yarn typecheck'
    displayName: 'Typecheck'

  - script: 'yarn generate && npx hardhat test'
    displayName: 'Hardhat Test'

  - script: 'yarn build'
    displayName: 'Build'
