version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devparty
    tty: true

  compiler:
    restart: unless-stopped
    image: node:16
    command: yarn codegen:graphql -- --watch
    volumes:
      - .:/srv/compiler:rw
    working_dir: /srv/compiler
