name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Install Yarn Dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Lint
        run: yarn lint

      - name: Prettier Check
        run: yarn prettier:check

      - name: Generate Prisma and GraphQL schema
        run: yarn generate

      - name: Typescript typecheck
        run: yarn typecheck

      - name: Build Devparty
        run: yarn build
